name: check-unexpected-access-key-header

on:
  push:
    paths:
      - "packages/web/src/app/*/e/**"
      - "packages/web/src/app/*/w/**"

jobs:
  check-slugs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/web
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: "https://npm.pkg.github.com"
      - run: pnpm install --frozen-lockfile
      - run: node --experimental-strip-types ./src/scripts/index.mts
